---

- name: bgpreflector-tests
  hosts: bgpreflector-tests
  gather_facts: no

  vars_files:
    - vars.yml

  roles:
    - cisco
    - bgpreflector


- name: bras-tests
  hosts: cisco-tests
  gather_facts: no

  vars_files:
    - vars.yml

  roles:
    - cisco
    - { role: bras, when: "'{{ applyToHosts }}' in {{ group_names }}" }

