- name: Abort if VRF already exists
  fail: msg="VRF {{ VRFname }} or rd {{ rd }} already exists"
  with_items: cisco.vrf.keys()
  when: "item == '{{ VRFname }}' or '{{ cisco.bgp.AS }}:{{ rd }}'  == cisco.vrf.{{ item }}.rd"

- name: Generate configuration file
  local_action: template src=addVRF.j2 dest={{ playbook_dir }}/roles/bras/files/addVRF force=yes

- name: execute changes
  local_action:
    cisco_exec_commands.py
      hostname="{{ inventory_hostname }}"
      username="{{ username }}"
      password="{{ password }}"
      enable="{{ enable }}"
      commandFile="{{ playbook_dir }}/roles/bras/files/addVRF"


